# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('compatible', models.CharField(max_length=30)),
                ('artifacts', models.ManyToManyField(to='deploy.Artifact')),
            ],
        ),
    ]
