# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
